---
- name: Install Docker and run NGINX container with a custom index.html
  hosts: localhost
  become: yes
  tasks:
    # Install necessary packages
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    # Get the local IP address
    - name: Get the local IP address
      shell: "hostname -I | awk '{print $1}'"
      register: local_ip

    # Create custom index.html
    - name: Create index.html file
      copy:
        content: |
          <html>
            <head><title>Hello from Docker NGINX!</title></head>
            <body><h1>Hello World from NGINX on Docker!</h1> 
            <p>Local IP: {{ local_ip.stdout }}</p>
            </body>
          </html>
        dest: /home/ec2-user/index.html

    # Run NGINX container with custom index.html
    - name: Run NGINX container
      command: >
        docker run -d --name nginx-container -p 80:80
        -v /home/ec2-user/index.html:/usr/share/nginx/html/index.html:ro nginx:latest
